# environment.yml
name: tiepoints
channels: !!python/tuple
- !!python/unicode
  'conda-forge'
- !!python/unicode
  'conda-forge/label/dev'
- !!python/unicode
  'defaults'
dependencies:
- conda-forge::blas=1.1=openblas
- conda-forge::openblas=0.2.19=2
- conda-forge::opencv=3.2.0=np113py27_blas_openblas_204
- conda-forge::python=2.7
- conda-forge/label/dev::rasterio=1.0a9
- conda-forge::pandas
- conda-forge::shapely
- pip:
  - tqdm
  - fiona
#  - gbdxtools